auth_host = "0.0.0.0"
auth_port = 4557
auth_reload = True

OPENAI_API_TYPE = "azure"
OPENAI_API_VERSION = "2023-05-15"
AZURE_OPENAI_API_KEY = ""
AZURE_OPENAI_ENDPOINT = ""
AZURE_OPENAI_DEPLOYMENT_NAME = "gpt-4"
