import os

from configurations import OPENAI_API_TYPE, OPENAI_API_VERSION, AZURE_OPENAI_API_KEY, AZURE_OPENAI_ENDPOINT

os.environ["OPENAI_API_TYPE"] = OPENAI_API_TYPE
os.environ["OPENAI_API_VERSION"] = OPENAI_API_VERSION
os.environ["OPENAI_API_KEY"] = AZURE_OPENAI_API_KEY
os.environ["OPENAI_API_BASE"] = AZURE_OPENAI_ENDPOINT